// Spawn
IF  Global("vvValkSpawn","GLOBAL",0)
    THEN
    RESPONSE #100
        //CreateCreature("vvVALK",[213.614],S)
        CreateCreature("vvVALK",[2085.1689],S)
        SetGlobal("vvValkSpawn","GLOBAL",1)
        Continue()
END

// To display invitation text in areas prior to meeting.
IF  Global("vvVALKMet","GLOBAL",0)
    Global("vvVALKNote","GLOBAL",0)
    THEN
    RESPONSE #100
        DisplayStringHead(Myself,@199)
        SetGlobal("vvVALKNote","GLOBAL",1)
        Continue()
END